### ISSUE TITLE
pizero-gpslog-convert switch (-o) fails to appropriately name file

### ISSUE THREAD

**Issue by ar4121** [jantman/pizero-gpslog#3]
This isn't a problem that causes the program to fail. It could be a coding issue or it could be that the documentation needs to be updated.

Taking a file, using the convert script with the -o output fails unless a specific filename is given.  So unless you actively input: 
pizero-gpslog-convert -o /path/to/file/loc/makeFilename.gpx   jsonFileToBeConverted.json

Normally, running the convert scripts without any switches appropriately renames the file the same name as the json file, in the same directory.  Using the -o switch will fail unless you rename the file as well as specify the output directory. This is counter to what the docs say.

From the docs:
> -o OUTPUT, --output OUTPUT
                        Output file path. By default, will be the input file
                        path with the file extension replaced with the correct
                        one for the output format.

`
root@GPSPI:/opt/GPS_DATA/json-files# pizero-gpslog-convert -o /opt/GPS_DATA/ 2018-11-07_14-10-08.json
Traceback (most recent call last):
  File "/usr/local/bin/pizero-gpslog-convert", line 11, in <module>
    load_entry_point('pizero-gpslog', 'console_scripts', 'pizero-gpslog-convert')()
  File "/opt/GPS/pizero-gpslog/pizero_gpslog/converter.py", line 194, in main
    stats=args.stats
  File "/opt/GPS/pizero-gpslog/pizero_gpslog/converter.py", line 83, in convert
    with open(self._out_fpath, 'w') as fh:
IsADirectoryError: [Errno 21] Is a directory: '/opt/GPS_DATA/'
`

Thanks,
again, this isn't a deal breaker, everything is working great so far.  I just wrote a few bash scripts to convert and move the files into specific folders that are served by a lighttpd webserver so I can download them this way instead of having to take the microSD out and manually select and load the files.

**Comment by jantman** [comment]
Apologies for taking so long to respond to this.

I suppose either the functionality should be changed or the help output could be clarified, but this is the intended behavior... it's asking for an output "file path", not directory, and an existing directory is an invalid path for a new file. The intended behavior (at least how I intended it, and how it's coded) is that either you leave off `-o` and take the default, or else you specify the absolute or relative path that you want it to write output to (i.e. `-o /tmp/a` would write the output to a file at `/tmp/a`).

Let me know if you think the help output needs to change to clarify this.
